[CmdletBinding()]
param(
    [string]$QuarantineRoot,
    [string]$InspectorScript,
    [string]$ReconId,
    [ValidatePattern('^state_[0-9a-f]{32}$')][string]$StateId,
    [ValidateRange(1,20)][int]$MaxFiles = 20,
    [string]$DockerExecutable
)
$ErrorActionPreference='Stop'
$script:Errors=@('input_reparse_point','state_reparse_point','output_reparse_point','invalid_sampling_state','invalid_report_schema','inspector_failed','invalid_state','unexpected_failure')
$script:Protocols=@('arp','dns','eth','http','http2','icmp','icmpv6','ip','ipv6','quic','sll','sll2','tcp','tls','udp','websocket')
$script:Vis=@('plaintext_application_protocol_observed','encrypted_transport_observed','tls_observed','quic_observed')
function Fail([string]$Code){throw [System.InvalidOperationException]::new($Code)}
function Assert-NoReparse([string]$Path,[string]$Code){
    $p=[IO.Path]::GetFullPath($Path); $root=[IO.Path]::GetPathRoot($p).TrimEnd('\','/')
    while($p){ if(Test-Path -LiteralPath $p){try{$a=[IO.File]::GetAttributes($p)}catch{Fail $Code};if(($a-band [IO.FileAttributes]::ReparsePoint)-ne 0){Fail $Code}}
        $t=$p.TrimEnd('\','/');if($t.Equals($root,[StringComparison]::OrdinalIgnoreCase)){break};$d=[IO.Directory]::GetParent($t);if($null -eq $d){break};$p=$d.FullName }
}
function Ensure-Dir([string]$Path,[string]$Code){Assert-NoReparse $Path $Code;New-Item -ItemType Directory -Path $Path -Force|Out-Null;Assert-NoReparse $Path $Code}
function Get-Sha256([string]$Path){$h=[Security.Cryptography.SHA256]::Create();$s=[IO.File]::OpenRead($Path);try{return (($h.ComputeHash($s)|%{$_.ToString('x2')})-join '')}finally{$s.Dispose();$h.Dispose()}}
function Atomic([object]$Value,[string]$Path){$tmp="$Path.$([Guid]::NewGuid().ToString('N')).tmp";try{[IO.File]::WriteAllText($tmp,($Value|ConvertTo-Json -Depth 10 -Compress),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $Path -Force}finally{if(Test-Path -LiteralPath $tmp){Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue}}}
function Ordered-Files([IO.DirectoryInfo]$Root){
    $all=[Collections.ArrayList]::new();$q=[Collections.Generic.Queue[IO.DirectoryInfo]]::new();$q.Enqueue($Root)
    while($q.Count){$d=$q.Dequeue();foreach($e in $d.GetFileSystemInfos()){if(($e.Attributes-band [IO.FileAttributes]::ReparsePoint)-ne 0){Fail 'input_reparse_point'};if($e -is [IO.DirectoryInfo]){$q.Enqueue($e)}elseif($e.Extension.ToLowerInvariant() -in @('.pcap','.pcapng')){[void]$all.Add([pscustomobject]@{File=$e;Ordinal=$e.FullName.Substring(($Root.FullName.TrimEnd('\','/')).Length+1)})}}}
    for($i=1;$i -lt $all.Count;$i++){ $x=$all[$i];$j=$i-1;while($j -ge 0 -and (($all[$j].File.Length -gt $x.File.Length)-or($all[$j].File.Length -eq $x.File.Length -and [string]::CompareOrdinal($all[$j].Ordinal,$x.Ordinal)-gt 0))){$all[$j+1]=$all[$j];$j--};$all[$j+1]=$x };return @($all)
}
function Quote([string]$Value){$b=New-Object Text.StringBuilder;[void]$b.Append('"');$slashes=0;foreach($c in $Value.ToCharArray()){if($c -eq [char]92){$slashes++;continue};if($c -eq '"'){[void]$b.Append(('\' * ($slashes*2+1)));}elseif($slashes){[void]$b.Append(('\' * $slashes))};[void]$b.Append($c);$slashes=0};if($slashes){[void]$b.Append(('\' * ($slashes*2)))};[void]$b.Append('"');$b.ToString()}
function Invoke-Inspector([string]$Script,[string]$Capture,[string]$Root,[string]$Docker){
    $ps=[IO.Path]::Combine($env:SystemRoot,'System32','WindowsPowerShell','v1.0','powershell.exe');$args=@('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',(Quote $Script),'-Path',(Quote $Capture),'-QuarantineRoot',(Quote $Root));if($Docker){$args+=@('-DockerExecutable',(Quote $Docker))}
    $si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=$ps;$si.Arguments=$args -join ' ';$si.UseShellExecute=$false;$si.CreateNoWindow=$true;$si.RedirectStandardOutput=$true;$si.RedirectStandardError=$true;$p=[Diagnostics.Process]::new();$p.StartInfo=$si
    try{if(-not $p.Start()){return 1};$o=$p.StandardOutput.ReadToEndAsync();$e=$p.StandardError.ReadToEndAsync();$p.WaitForExit();[void]$o.Result;[void]$e.Result;return $p.ExitCode}finally{$p.Dispose()}
}
function Valid-Child([object]$R,[int64]$Size){
    $keys=@($R.PSObject.Properties.Name);$expected=@('schema_version','sha256','size_bytes','capture_format','packet_count','duration_seconds','link_types','protocol_counts','visibility','capability','reasons','tool_versions');if($keys.Count-ne $expected.Count -or @($expected|Where-Object{$keys-notcontains $_}).Count){Fail 'invalid_report_schema'}
    if($R.schema_version-ne 1 -or $R.sha256 -notmatch '^[0-9a-f]{64}$' -or $R.size_bytes-ne $Size -or @('pcap','pcapng')-notcontains $R.capture_format -or $R.packet_count -isnot [int64] -and $R.packet_count -isnot [int32] -or $R.packet_count -lt 0 -or $R.duration_seconds -isnot [double] -and $R.duration_seconds -isnot [int] -and $R.duration_seconds -isnot [decimal] -or $R.duration_seconds -lt 0 -or $R.link_types -isnot [array] -or $R.reasons -isnot [array] -or $R.tool_versions.tshark -isnot [string]){Fail 'invalid_report_schema'}
    if($R.link_types -isnot [array] -or $R.link_types.Count -ne (@($R.link_types|Sort-Object -Unique).Count)){Fail 'invalid_report_schema'};foreach($l in $R.link_types){if($l -notmatch '^encap_[0-9]+$'){Fail 'invalid_report_schema'}}
    $pn=@($R.protocol_counts.PSObject.Properties.Name);foreach($n in $pn){if($script:Protocols-notcontains $n -or $R.protocol_counts.$n -isnot [int64] -and $R.protocol_counts.$n -isnot [int32] -or $R.protocol_counts.$n -lt 0){Fail 'invalid_report_schema'}};if(@($pn|Sort-Object).Count -ne $pn.Count){Fail 'invalid_report_schema'}
    if(@($R.visibility.PSObject.Properties.Name).Count-ne 4){Fail 'invalid_report_schema'};foreach($n in $script:Vis){if($R.visibility.$n -isnot [bool]){Fail 'invalid_report_schema'}}
    if($R.visibility.plaintext_application_protocol_observed -ne (($R.protocol_counts.http -gt 0)-or($R.protocol_counts.http2 -gt 0)-or($R.protocol_counts.websocket -gt 0))){Fail 'invalid_report_schema'};if($R.visibility.encrypted_transport_observed -ne (($R.protocol_counts.tls -gt 0)-or($R.protocol_counts.quic -gt 0))){Fail 'invalid_report_schema'}
    if(@('token_eligible','traffic_only','insufficient_evidence')-notcontains $R.capability -or $R.reasons -isnot [array] -or $R.tool_versions.tshark -notmatch '^(?:tshark|TShark [0-9]+\.[0-9]+\.[0-9]+)$'){Fail 'invalid_report_schema'}
    return $R
}
try{
    if($ReconId -notmatch '^recon_[0-9a-f]{32}$'){Fail 'unexpected_failure'}
    $root=[IO.Path]::GetFullPath($QuarantineRoot);$input=[IO.Path]::Combine($root,'input');$out=[IO.Path]::Combine($root,'output');$stateDir=[IO.Path]::Combine($root,'state');Ensure-Dir $input 'input_reparse_point';Ensure-Dir $out 'output_reparse_point';Ensure-Dir $stateDir 'state_reparse_point'
    $statePath=[IO.Path]::Combine($stateDir,'pcap-recon-private.json');Assert-NoReparse $statePath 'state_reparse_point';$state=[ordered]@{schema_version=1;state_id=$StateId;entries=@()};if(Test-Path -LiteralPath $statePath){try{$state=[IO.File]::ReadAllText($statePath)|ConvertFrom-Json -ErrorAction Stop}catch{Fail 'invalid_state'};if($state.schema_version-ne 1 -or $state.state_id-ne $StateId -or $null -eq $state.entries){Fail 'invalid_state'};foreach($se in @($state.entries)){if($se.internal_path -isnot [string] -or $se.sha256 -notmatch '^[0-9a-f]{64}$' -or $se.size_bytes -isnot [int64] -and $se.size_bytes -isnot [int32] -or $se.size_bytes -lt 0 -or @('succeeded','failed')-notcontains $se.status -or $se.error_code -and $se.error_code -notmatch '^[a-z0-9_]+$'){Fail 'invalid_state'}}}
    $cancel=[IO.Path]::Combine($stateDir,($ReconId+'.cancel'));$files=@(Ordered-Files (Get-Item -LiteralPath $input));$n=$files.Count;$selected=[Collections.ArrayList]::new();if($n){$groups=@(@(),@(),@(),@());for($i=0;$i-lt $n;$i++){ $q=[Math]::Min(3,[Math]::Floor($i*4/$n));$groups[$q]+=$files[$i] };for($q=0;$q-lt 4;$q++){ $m=$groups[$q].Count;$s=[Math]::Min(5,$m);$seen=@{};for($k=0;$k-lt $s;$k++){ $idx=[Math]::Floor((($k+0.5)*$m)/$s);if($seen.ContainsKey($idx)){Fail 'invalid_sampling_state'};$seen[$idx]=$true;[void]$selected.Add($groups[$q][$idx]) }}}
    if($selected.Count -gt $MaxFiles){$selected=@($selected|Select-Object -First $MaxFiles)}
    $hist=[ordered]@{schema_version=1;sampled_count=0;succeeded_count=0;failed_count=0;quartile_counts=[ordered]@{quartile_1=0;quartile_2=0;quartile_3=0;quartile_4=0};size_bucket_counts=[ordered]@{under_2_kib=0;two_kib_to_64_kib=0;sixty_four_kib_to_1_mib=0;at_least_1_mib=0};packet_bucket_counts=[ordered]@{empty=0;one_to_15=0;sixteen_to_63=0;at_least_64=0};duration_bucket_counts=[ordered]@{zero=0;under_1_second=0;one_to_10_seconds=0;over_10_seconds=0};protocol_presence_counts=[ordered]@{};plaintext_sample_count=0;encrypted_sample_count=0;sequence_candidate_count=0}
    $entries=[Collections.ArrayList]::new();foreach($e in @($state.entries)){[void]$entries.Add($e)}
    foreach($c in $selected){if(Test-Path -LiteralPath $cancel){Remove-Item -LiteralPath $cancel -Force -ErrorAction SilentlyContinue;break};$ord=$c.Ordinal;$prior=@($entries|Where-Object{$_.internal_path -eq $ord})|Select-Object -First 1;$r=$null;$status='failed';$err='inspector_failed';$new=@();$before=@(Get-ChildItem -LiteralPath $out -Filter 'pcap-preflight-*.json' -File -ErrorAction SilentlyContinue);foreach($stale in $before){Remove-Item -LiteralPath $stale.FullName -Force -ErrorAction SilentlyContinue};try{$code=Invoke-Inspector $InspectorScript $c.File.FullName $root $DockerExecutable;if($code-ne 0){Fail 'inspector_failed'};$after=@(Get-ChildItem -LiteralPath $out -Filter 'pcap-preflight-*.json' -File -ErrorAction SilentlyContinue);$new=$after;if($new.Count-ne 1){Fail 'invalid_report_schema'};$r=Valid-Child ([IO.File]::ReadAllText($new[0].FullName)|ConvertFrom-Json) $c.File.Length;if($r.sha256 -ne (Get-Sha256 $c.File.FullName)){Fail 'invalid_report_schema'};$status='succeeded';$err=$null} catch {$err=if($_.Exception.Message -eq 'invalid_report_schema'){'invalid_report_schema'}else{'inspector_failed'}} finally{foreach($x in @($new)){Remove-Item -LiteralPath $x.FullName -Force -ErrorAction SilentlyContinue}}
        $hist.sampled_count++;$q=[Math]::Min(3,[Math]::Floor(([array]$files).IndexOf($c)*4/$n));$hist.quartile_counts['quartile_'+($q+1)]++;if($status -eq 'succeeded'){$hist.succeeded_count++;$size=$c.File.Length;if($size -lt 2048){$hist.size_bucket_counts.under_2_kib++}elseif($size -lt 65536){$hist.size_bucket_counts.two_kib_to_64_kib++}elseif($size -lt 1048576){$hist.size_bucket_counts.sixty_four_kib_to_1_mib++}else{$hist.size_bucket_counts.at_least_1_mib++};$pc=[int64]$r.packet_count;if($pc -eq 0){$hist.packet_bucket_counts.empty++}elseif($pc -le 15){$hist.packet_bucket_counts.one_to_15++}elseif($pc -le 63){$hist.packet_bucket_counts.sixteen_to_63++}else{$hist.packet_bucket_counts.at_least_64++;$hist.sequence_candidate_count++};$d=[double]$r.duration_seconds;if($d -eq 0){$hist.duration_bucket_counts.zero++}elseif($d -lt 1){$hist.duration_bucket_counts.under_1_second++}elseif($d -le 10){$hist.duration_bucket_counts.one_to_10_seconds++}else{$hist.duration_bucket_counts.over_10_seconds++};if($r.visibility.plaintext_application_protocol_observed){$hist.plaintext_sample_count++};if($r.visibility.encrypted_transport_observed){$hist.encrypted_sample_count++};foreach($p in @($r.protocol_counts.PSObject.Properties)){if($p.Value -gt 0){if(-not $hist.protocol_presence_counts.Contains($p.Name)){$hist.protocol_presence_counts[$p.Name]=0};$hist.protocol_presence_counts[$p.Name]++}}}
        foreach($left in @(Get-ChildItem -LiteralPath $out -Filter 'pcap-preflight-*.json' -File -ErrorAction SilentlyContinue)){Remove-Item -LiteralPath $left.FullName -Force -ErrorAction SilentlyContinue};$entry=[ordered]@{internal_path=$ord;sha256=if($r){$r.sha256}else{Get-Sha256 $c.File.FullName};size_bytes=[int64]$c.File.Length;status=$status;error_code=$err;packet_count=if($r){$r.packet_count}else{0};duration_seconds=if($r){$r.duration_seconds}else{0};protocol_counts=if($r){$r.protocol_counts}else{[ordered]@{}};visibility=if($r){$r.visibility}else{[ordered]@{}}};$old=@($entries|Where-Object{$_.internal_path-ne $ord});$entries=[Collections.ArrayList]@($old);[void]$entries.Add($entry);Atomic ([ordered]@{schema_version=1;state_id=$StateId;entries=@($entries)}) $statePath }
    Atomic ([ordered]@{schema_version=1;state_id=$StateId;entries=@($entries)}) $statePath;$pub=[IO.Path]::Combine($out,('pcap-recon-'+$ReconId+'.json'));Assert-NoReparse $pub 'output_reparse_point';Atomic $hist $pub;Write-Output ('pcap_recon_result='+$ReconId);exit 0
}catch{$code='unexpected_failure';if($script:Errors-contains $_.Exception.Message){$code=$_.Exception.Message};Write-Output ('pcap_recon_error='+$code);exit 2}
