[CmdletBinding()]
param(
    [string]$QuarantineRoot,
    [string]$InspectorScript,
    [string]$ReconId,
    [ValidatePattern('^state_[0-9a-f]{32}$')][string]$StateId,
    [ValidateRange(1,10000)][int]$MaxFiles = 100,
    [string]$DockerExecutable
)

$ErrorActionPreference = 'Stop'
$script:ErrorCodes = @('input_reparse_point', 'state_reparse_point', 'output_reparse_point', 'invalid_sampling_state', 'invalid_report_schema', 'inspector_failed', 'invalid_state', 'unexpected_failure')
$script:AllowedProtocols = @('arp', 'dns', 'eth', 'http', 'http2', 'icmp', 'icmpv6', 'ip', 'ipv6', 'quic', 'sll', 'sll2', 'tcp', 'tls', 'udp', 'websocket')
$script:VisibilityKeys = @('plaintext_application_protocol_observed', 'encrypted_transport_observed', 'tls_observed', 'quic_observed')
$script:ChildReportKeys = @('schema_version', 'sha256', 'size_bytes', 'capture_format', 'packet_count', 'duration_seconds', 'link_types', 'protocol_counts', 'visibility', 'capability', 'reasons', 'tool_versions')
$script:PrivateStateKeys = @('schema_version', 'state_id', 'entries')
$script:PrivateEntryKeys = @('internal_path', 'sha256', 'size_bytes', 'status', 'error_code', 'packet_count', 'duration_seconds', 'protocol_counts', 'visibility')

function Fail([string]$Code) { throw [System.InvalidOperationException]::new($Code) }
function Get-Names($Value, [string]$Code = 'invalid_report_schema') { if ($null -eq $Value -or $Value -isnot [pscustomobject]) { Fail $Code }; return @($Value.PSObject.Properties | ForEach-Object { $_.Name }) }
function Test-ExactKeys($Value, [string[]]$Expected, [string]$Code = 'invalid_report_schema') { $actual = @(Get-Names $Value $Code); if ($actual.Count -ne $Expected.Count) { Fail $Code }; foreach ($name in $Expected) { if ($actual -notcontains $name) { Fail $Code } } }
function Test-NonnegativeInteger($Value) { if ($Value -is [bool]) { return $false }; if ($Value -isnot [byte] -and $Value -isnot [int16] -and $Value -isnot [int32] -and $Value -isnot [int64] -and $Value -isnot [uint16] -and $Value -isnot [uint32] -and $Value -isnot [uint64]) { return $false }; return $Value -ge 0 -and $Value -le [int64]::MaxValue }
function Test-FiniteNonnegativeNumber($Value) { if ($Value -is [bool] -or ($Value -isnot [double] -and $Value -isnot [single] -and $Value -isnot [decimal] -and $Value -isnot [int] -and $Value -isnot [long])) { return $false }; $number = [double]$Value; return -not [double]::IsNaN($number) -and -not [double]::IsInfinity($number) -and $number -ge 0 }
function Test-SortedUniqueStrings($Value) { if ($Value -isnot [array]) { return $false }; $previous = $null; $hasPrevious = $false; foreach ($item in $Value) { if ($item -isnot [string]) { return $false }; if ($hasPrevious -and [string]::CompareOrdinal($previous, $item) -ge 0) { return $false }; $previous = $item; $hasPrevious = $true }; return $true }

function Assert-NoReparse([string]$Path, [string]$Code) {
    $current = [IO.Path]::GetFullPath($Path); $root = [IO.Path]::GetPathRoot($current).TrimEnd([char]'\', [char]'/')
    while (-not [string]::IsNullOrWhiteSpace($current)) {
        if (Test-Path -LiteralPath $current) { try { $attributes = [IO.File]::GetAttributes($current) } catch { Fail $Code }; if (($attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { Fail $Code } }
        $trimmed = $current.TrimEnd([char]'\', [char]'/'); if ($trimmed.Equals($root, [StringComparison]::OrdinalIgnoreCase)) { break }; $parent = [IO.Directory]::GetParent($trimmed); if ($null -eq $parent) { break }; $current = $parent.FullName
    }
}
function Ensure-Directory([string]$Path, [string]$Code) { Assert-NoReparse $Path $Code; New-Item -ItemType Directory -Path $Path -Force | Out-Null; Assert-NoReparse $Path $Code }
function Get-Sha256Hex([string]$Path) { $algorithm = [Security.Cryptography.SHA256]::Create(); $stream = [IO.File]::OpenRead($Path); try { return (($algorithm.ComputeHash($stream) | ForEach-Object { $_.ToString('x2') }) -join '') } finally { $stream.Dispose(); $algorithm.Dispose() } }
function Save-AtomicJson($Value, [string]$Destination) { $directory = [IO.Path]::GetDirectoryName($Destination); $temporary = Join-Path $directory (([IO.Path]::GetFileName($Destination)) + '.' + [Guid]::NewGuid().ToString('N') + '.tmp'); try { [IO.File]::WriteAllText($temporary, ($Value | ConvertTo-Json -Depth 12 -Compress), [Text.UTF8Encoding]::new($false)); Move-Item -LiteralPath $temporary -Destination $Destination -Force } finally { if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force -ErrorAction SilentlyContinue } } }

function Get-OrderedFiles([IO.DirectoryInfo]$InputRoot) {
    $prefix = $InputRoot.FullName.TrimEnd([char]'\', [char]'/') + [IO.Path]::DirectorySeparatorChar; $queue = [Collections.Generic.Queue[IO.DirectoryInfo]]::new(); $queue.Enqueue($InputRoot); $items = [Collections.ArrayList]::new()
    while ($queue.Count -gt 0) { $directory = $queue.Dequeue(); foreach ($entry in $directory.GetFileSystemInfos()) { if (($entry.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { Fail 'input_reparse_point' }; if ($entry -is [IO.DirectoryInfo]) { $queue.Enqueue($entry); continue }; if ($entry -is [IO.FileInfo] -and $entry.Extension.ToLowerInvariant() -in @('.pcap', '.pcapng')) { [void]$items.Add([pscustomobject]@{ File = $entry; Ordinal = $entry.FullName.Substring($prefix.Length) }) } } }
    for ($i = 1; $i -lt $items.Count; $i++) { $candidate = $items[$i]; $j = $i - 1; while ($j -ge 0 -and (($items[$j].File.Length -gt $candidate.File.Length) -or (($items[$j].File.Length -eq $candidate.File.Length) -and [string]::CompareOrdinal($items[$j].Ordinal, $candidate.Ordinal) -gt 0))) { $items[$j + 1] = $items[$j]; $j-- }; $items[$j + 1] = $candidate }; return @($items)
}
function Select-Samples($Files, [int]$Limit) {
    if ($Files.Count -eq 0) { return @() }; $sampleCount = [int][Math]::Min($Limit, $Files.Count); $selected = [Collections.ArrayList]::new(); $seen = @{}
    for ($k = 0; $k -lt $sampleCount; $k++) { $index = [int][Math]::Floor((($k + 0.5) * $Files.Count) / $sampleCount); if ($seen.ContainsKey($index)) { Fail 'invalid_sampling_state' }; $seen[$index] = $true; $quartile = [int][Math]::Min(3, [Math]::Floor(($index * 4) / $Files.Count)); [void]$selected.Add([pscustomobject]@{ File = $Files[$index].File; Ordinal = $Files[$index].Ordinal; Quartile = $quartile }) }
    return @($selected)
}

function Assert-ValidProtocolCounts($Counts, [string]$Code) { $names = @(Get-Names $Counts $Code); for ($i = 0; $i -lt $names.Count; $i++) { $name = $names[$i]; if ($script:AllowedProtocols -notcontains $name -or -not (Test-NonnegativeInteger $Counts.$name)) { Fail $Code }; if ($i -gt 0 -and [string]::CompareOrdinal($names[$i - 1], $name) -ge 0) { Fail $Code } } }
function Get-ExpectedPolicy([int64]$PacketCount, $Counts) { if ($PacketCount -eq 0) { return @('insufficient_evidence', @('no_packets')) }; foreach ($name in @('http', 'http2', 'websocket')) { if ($Counts.PSObject.Properties[$name] -and $Counts.$name -gt 0) { return @('token_eligible', @('plaintext_application_protocol_observed')) } }; foreach ($name in @('tls', 'quic')) { if ($Counts.PSObject.Properties[$name] -and $Counts.$name -gt 0) { return @('traffic_only', @('encrypted_transport_observed')) } }; $total = [int64]0; foreach ($property in $Counts.PSObject.Properties) { $total += [int64]$property.Value }; if ($total -gt 0) { return @('traffic_only', @('network_traffic_only')) }; return @('insufficient_evidence', @('no_supported_protocols')) }

function Convert-ChildReport($Report, [string]$ExpectedSha, [int64]$ExpectedSize, [string]$ExpectedFormat) {
    Test-ExactKeys $Report $script:ChildReportKeys 'invalid_report_schema'; if (-not (Test-NonnegativeInteger $Report.schema_version) -or $Report.schema_version -ne 1) { Fail 'invalid_report_schema' }; if ($Report.sha256 -isnot [string] -or $Report.sha256 -notmatch '^[0-9a-f]{64}$' -or $Report.sha256 -ne $ExpectedSha) { Fail 'invalid_report_schema' }; if (-not (Test-NonnegativeInteger $Report.size_bytes) -or [int64]$Report.size_bytes -ne $ExpectedSize) { Fail 'invalid_report_schema' }; if (@('pcap', 'pcapng') -notcontains $Report.capture_format -or $Report.capture_format -ne $ExpectedFormat) { Fail 'invalid_report_schema' }; if (-not (Test-NonnegativeInteger $Report.packet_count) -or -not (Test-FiniteNonnegativeNumber $Report.duration_seconds)) { Fail 'invalid_report_schema' }; if (-not (Test-SortedUniqueStrings $Report.link_types)) { Fail 'invalid_report_schema' }; foreach ($link in $Report.link_types) { if ($link -notmatch '^encap_[0-9]+$') { Fail 'invalid_report_schema' } }; Assert-ValidProtocolCounts $Report.protocol_counts 'invalid_report_schema'; Test-ExactKeys $Report.visibility $script:VisibilityKeys 'invalid_report_schema'; foreach ($name in $script:VisibilityKeys) { if ($Report.visibility.$name -isnot [bool]) { Fail 'invalid_report_schema' } }
    $expectedVisibility = [ordered]@{ plaintext_application_protocol_observed = (($Report.protocol_counts.http -gt 0) -or ($Report.protocol_counts.http2 -gt 0) -or ($Report.protocol_counts.websocket -gt 0)); encrypted_transport_observed = (($Report.protocol_counts.tls -gt 0) -or ($Report.protocol_counts.quic -gt 0)); tls_observed = ($Report.protocol_counts.tls -gt 0); quic_observed = ($Report.protocol_counts.quic -gt 0) }; foreach ($name in $script:VisibilityKeys) { if ($Report.visibility.$name -ne $expectedVisibility[$name]) { Fail 'invalid_report_schema' } }
    if (@('token_eligible', 'traffic_only', 'insufficient_evidence') -notcontains $Report.capability -or -not (Test-SortedUniqueStrings $Report.reasons)) { Fail 'invalid_report_schema' }; foreach ($reason in $Report.reasons) { if (@('plaintext_application_protocol_observed', 'encrypted_transport_observed', 'network_traffic_only', 'no_packets', 'no_supported_protocols') -notcontains $reason) { Fail 'invalid_report_schema' } }; $policy = Get-ExpectedPolicy ([int64]$Report.packet_count) $Report.protocol_counts; if ($Report.capability -ne $policy[0] -or $Report.reasons.Count -ne $policy[1].Count -or $Report.reasons[0] -ne $policy[1][0]) { Fail 'invalid_report_schema' }; Test-ExactKeys $Report.tool_versions @('tshark') 'invalid_report_schema'; if ($Report.tool_versions.tshark -isnot [string] -or $Report.tool_versions.tshark -notmatch '^(?:tshark|TShark [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})$') { Fail 'invalid_report_schema' }
    $protocols = [ordered]@{}; foreach ($property in $Report.protocol_counts.PSObject.Properties) { $protocols[$property.Name] = [int64]$property.Value }; return [ordered]@{ status = 'succeeded'; error_code = $null; packet_count = [int64]$Report.packet_count; duration_seconds = [double]$Report.duration_seconds; protocol_counts = $protocols; visibility = [ordered]@{ plaintext_application_protocol_observed = $Report.visibility.plaintext_application_protocol_observed; encrypted_transport_observed = $Report.visibility.encrypted_transport_observed; tls_observed = $Report.visibility.tls_observed; quic_observed = $Report.visibility.quic_observed } }
}

function Assert-ValidPrivateEntry($Entry) {
    Test-ExactKeys $Entry $script:PrivateEntryKeys 'invalid_state'; if ($Entry.internal_path -isnot [string] -or [string]::IsNullOrWhiteSpace($Entry.internal_path) -or [IO.Path]::IsPathRooted($Entry.internal_path)) { Fail 'invalid_state' }; foreach ($part in ($Entry.internal_path -split '[\\/]')) { if ($part -eq '..' -or $part -eq '.') { Fail 'invalid_state' } }; if ($Entry.sha256 -isnot [string] -or $Entry.sha256 -notmatch '^[0-9a-f]{64}$' -or -not (Test-NonnegativeInteger $Entry.size_bytes)) { Fail 'invalid_state' }; if (@('succeeded', 'failed') -notcontains $Entry.status) { Fail 'invalid_state' }; if ($null -ne $Entry.error_code -and @('inspector_failed', 'invalid_report_schema') -notcontains $Entry.error_code) { Fail 'invalid_state' }; if (-not (Test-NonnegativeInteger $Entry.packet_count) -or -not (Test-FiniteNonnegativeNumber $Entry.duration_seconds)) { Fail 'invalid_state' }; Assert-ValidProtocolCounts $Entry.protocol_counts 'invalid_state'; Test-ExactKeys $Entry.visibility $script:VisibilityKeys 'invalid_state'; foreach ($name in $script:VisibilityKeys) { if ($Entry.visibility.$name -isnot [bool]) { Fail 'invalid_state' } }; $expected = [ordered]@{ plaintext_application_protocol_observed = (($Entry.protocol_counts.http -gt 0) -or ($Entry.protocol_counts.http2 -gt 0) -or ($Entry.protocol_counts.websocket -gt 0)); encrypted_transport_observed = (($Entry.protocol_counts.tls -gt 0) -or ($Entry.protocol_counts.quic -gt 0)); tls_observed = ($Entry.protocol_counts.tls -gt 0); quic_observed = ($Entry.protocol_counts.quic -gt 0) }; foreach ($name in $script:VisibilityKeys) { if ($Entry.visibility.$name -ne $expected[$name]) { Fail 'invalid_state' } }; if ($Entry.status -eq 'succeeded' -and $null -ne $Entry.error_code) { Fail 'invalid_state' }; if ($Entry.status -eq 'failed' -and ($null -eq $Entry.error_code -or $Entry.packet_count -ne 0 -or $Entry.duration_seconds -ne 0 -or @($Entry.protocol_counts.PSObject.Properties).Count -ne 0)) { Fail 'invalid_state' }
}
function Read-PrivateState([string]$Path) { if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return [pscustomobject]@{ schema_version = 1; state_id = $StateId; entries = @() } }; try { $state = [IO.File]::ReadAllText($Path) | ConvertFrom-Json -ErrorAction Stop } catch { Fail 'invalid_state' }; Test-ExactKeys $state $script:PrivateStateKeys 'invalid_state'; if (-not (Test-NonnegativeInteger $state.schema_version) -or $state.schema_version -ne 1 -or $state.state_id -isnot [string] -or $state.entries -isnot [array]) { Fail 'invalid_state' }; $seen = @{}; foreach ($entry in @($state.entries)) { Assert-ValidPrivateEntry $entry; if ($seen.ContainsKey($entry.internal_path)) { Fail 'invalid_state' }; $seen[$entry.internal_path] = $true }; if ($state.state_id -ne $StateId) { return [pscustomobject]@{ schema_version = 1; state_id = $StateId; entries = @() } }; return $state }
function Find-Entry($Entries, [string]$Ordinal) { foreach ($entry in @($Entries)) { if ($entry.internal_path -ceq $Ordinal) { return $entry } }; return $null }
function Set-Entry([Collections.ArrayList]$Entries, $Entry) { for ($i = $Entries.Count - 1; $i -ge 0; $i--) { if ($Entries[$i].internal_path -ceq $Entry.internal_path) { $Entries.RemoveAt($i) } }; [void]$Entries.Add($Entry) }
function Remove-ChildReports([string]$OutputPath) { foreach ($file in @(Get-ChildItem -LiteralPath $OutputPath -Filter 'pcap-preflight-*.json' -File -ErrorAction SilentlyContinue)) { if (($file.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { Fail 'output_reparse_point' }; Remove-Item -LiteralPath $file.FullName -Force -ErrorAction SilentlyContinue } }
function Quote-ProcessArgument([string]$Value) { $builder = New-Object Text.StringBuilder; [void]$builder.Append([char]34); $slashes = 0; foreach ($character in $Value.ToCharArray()) { if ($character -eq [char]92) { $slashes++; continue }; if ($character -eq [char]34) { [void]$builder.Append(('\' * ($slashes * 2 + 1))) } elseif ($slashes -gt 0) { [void]$builder.Append(('\' * $slashes)) }; [void]$builder.Append($character); $slashes = 0 }; if ($slashes -gt 0) { [void]$builder.Append(('\' * ($slashes * 2))) }; [void]$builder.Append([char]34); return $builder.ToString() }
function Invoke-Inspector([string]$Script, [string]$Capture, [string]$Root, [string]$Docker) { $powershell = [IO.Path]::Combine($env:SystemRoot, 'System32', 'WindowsPowerShell', 'v1.0', 'powershell.exe'); $arguments = @('-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', (Quote-ProcessArgument $Script), '-Path', (Quote-ProcessArgument $Capture), '-QuarantineRoot', (Quote-ProcessArgument $Root)); if (-not [string]::IsNullOrWhiteSpace($Docker)) { $arguments += @('-DockerExecutable', (Quote-ProcessArgument $Docker)) }; $start = [Diagnostics.ProcessStartInfo]::new(); $start.FileName = $powershell; $start.Arguments = $arguments -join ' '; $start.UseShellExecute = $false; $start.CreateNoWindow = $true; $start.RedirectStandardOutput = $true; $start.RedirectStandardError = $true; $process = [Diagnostics.Process]::new(); $process.StartInfo = $start; try { if (-not $process.Start()) { return 1 }; $stdout = $process.StandardOutput.ReadToEndAsync(); $stderr = $process.StandardError.ReadToEndAsync(); $process.WaitForExit(); [void]$stdout.Result; [void]$stderr.Result; return $process.ExitCode } finally { $process.Dispose() } }
function New-FailedEntry([string]$Ordinal, [string]$Sha, [int64]$Size, [string]$Code) { return [ordered]@{ internal_path = $Ordinal; sha256 = $Sha; size_bytes = $Size; status = 'failed'; error_code = $Code; packet_count = [int64]0; duration_seconds = [double]0; protocol_counts = [ordered]@{}; visibility = [ordered]@{ plaintext_application_protocol_observed = $false; encrypted_transport_observed = $false; tls_observed = $false; quic_observed = $false } } }
function New-Histogram { return [ordered]@{ schema_version = 1; sampled_count = 0; succeeded_count = 0; failed_count = 0; quartile_counts = [ordered]@{ quartile_1 = 0; quartile_2 = 0; quartile_3 = 0; quartile_4 = 0 }; size_bucket_counts = [ordered]@{ under_2_kib = 0; '2_kib_to_64_kib' = 0; '64_kib_to_1_mib' = 0; at_least_1_mib = 0 }; packet_bucket_counts = [ordered]@{ empty = 0; '1_to_15' = 0; '16_to_63' = 0; at_least_64 = 0 }; duration_bucket_counts = [ordered]@{ zero = 0; under_1_second = 0; '1_to_10_seconds' = 0; over_10_seconds = 0 }; protocol_presence_counts = [ordered]@{}; plaintext_sample_count = 0; encrypted_sample_count = 0; sequence_candidate_count = 0 } }
function Add-ToHistogram($Histogram, $Entry, [int]$Quartile) { $Histogram.sampled_count++; $Histogram.quartile_counts['quartile_' + ($Quartile + 1)]++; if ($Entry.status -eq 'failed') { $Histogram.failed_count++; return }; $Histogram.succeeded_count++; if ($Entry.size_bytes -lt 2048) { $Histogram.size_bucket_counts.under_2_kib++ } elseif ($Entry.size_bytes -lt 65536) { $Histogram.size_bucket_counts['2_kib_to_64_kib']++ } elseif ($Entry.size_bytes -lt 1048576) { $Histogram.size_bucket_counts['64_kib_to_1_mib']++ } else { $Histogram.size_bucket_counts.at_least_1_mib++ }; if ($Entry.packet_count -eq 0) { $Histogram.packet_bucket_counts.empty++ } elseif ($Entry.packet_count -le 15) { $Histogram.packet_bucket_counts['1_to_15']++ } elseif ($Entry.packet_count -le 63) { $Histogram.packet_bucket_counts['16_to_63']++ } else { $Histogram.packet_bucket_counts.at_least_64++; $Histogram.sequence_candidate_count++ }; if ($Entry.duration_seconds -eq 0) { $Histogram.duration_bucket_counts.zero++ } elseif ($Entry.duration_seconds -lt 1) { $Histogram.duration_bucket_counts.under_1_second++ } elseif ($Entry.duration_seconds -le 10) { $Histogram.duration_bucket_counts['1_to_10_seconds']++ } else { $Histogram.duration_bucket_counts.over_10_seconds++ }; if ($Entry.visibility.plaintext_application_protocol_observed) { $Histogram.plaintext_sample_count++ }; if ($Entry.visibility.encrypted_transport_observed) { $Histogram.encrypted_sample_count++ }; if ($Entry.protocol_counts -is [Collections.IDictionary]) { foreach ($property in $Entry.protocol_counts.GetEnumerator()) { if ($property.Value -gt 0) { if (-not $Histogram.protocol_presence_counts.Contains($property.Key)) { $Histogram.protocol_presence_counts[$property.Key] = 0 }; $Histogram.protocol_presence_counts[$property.Key]++ } } } else { foreach ($property in $Entry.protocol_counts.PSObject.Properties) { if ($property.Value -gt 0) { if (-not $Histogram.protocol_presence_counts.Contains($property.Name)) { $Histogram.protocol_presence_counts[$property.Name] = 0 }; $Histogram.protocol_presence_counts[$property.Name]++ } } } }

try {
    if ($ReconId -notmatch '^recon_[0-9a-f]{32}$' -or $StateId -notmatch '^state_[0-9a-f]{32}$' -or [string]::IsNullOrWhiteSpace($QuarantineRoot) -or [string]::IsNullOrWhiteSpace($InspectorScript)) { Fail 'unexpected_failure' }
    $root = [IO.Path]::GetFullPath($QuarantineRoot); $inputPath = Join-Path $root 'input'; $outputPath = Join-Path $root 'output'; $stateDir = Join-Path $root 'state'; Ensure-Directory $inputPath 'input_reparse_point'; Ensure-Directory $outputPath 'output_reparse_point'; Ensure-Directory $stateDir 'state_reparse_point'
    $stateFile = Join-Path $stateDir 'pcap-recon-private.json'; Assert-NoReparse $stateFile 'state_reparse_point'; $state = Read-PrivateState $stateFile; $entries = [Collections.ArrayList]::new(); foreach ($entry in @($state.entries)) { [void]$entries.Add($entry) }
    $cancelPath = Join-Path $stateDir ($ReconId + '.cancel'); Remove-ChildReports $outputPath; $files = @(Get-OrderedFiles (Get-Item -LiteralPath $inputPath)); $selected = @(Select-Samples $files $MaxFiles); $histogram = New-Histogram; $processedSinceCheckpoint = 0
    foreach ($candidate in $selected) {
        if (Test-Path -LiteralPath $cancelPath -PathType Leaf) { Remove-Item -LiteralPath $cancelPath -Force -ErrorAction SilentlyContinue; break }
        Assert-NoReparse $candidate.File.FullName 'input_reparse_point'; $sha = Get-Sha256Hex $candidate.File.FullName; $size = [int64]$candidate.File.Length; $format = if ($candidate.File.Extension.ToLowerInvariant() -eq '.pcapng') { 'pcapng' } else { 'pcap' }; $prior = Find-Entry $entries $candidate.Ordinal
        if ($null -ne $prior -and $prior.status -eq 'succeeded' -and $prior.sha256 -eq $sha -and [int64]$prior.size_bytes -eq $size) { Add-ToHistogram $histogram $prior $candidate.Quartile; continue }
        $entry = $null; Remove-ChildReports $outputPath
        try {
            $exitCode = Invoke-Inspector $InspectorScript $candidate.File.FullName $root $DockerExecutable; $childReports = @(Get-ChildItem -LiteralPath $outputPath -Filter 'pcap-preflight-*.json' -File -ErrorAction SilentlyContinue); if ($exitCode -ne 0) { Fail 'inspector_failed' }; if ($childReports.Count -ne 1) { Fail 'invalid_report_schema' }; if (($childReports[0].Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { Fail 'output_reparse_point' }; try { $report = [IO.File]::ReadAllText($childReports[0].FullName) | ConvertFrom-Json -ErrorAction Stop } catch { Fail 'invalid_report_schema' }; $metrics = Convert-ChildReport $report $sha $size $format; $entry = [ordered]@{ internal_path = $candidate.Ordinal; sha256 = $sha; size_bytes = $size; status = 'succeeded'; error_code = $null; packet_count = $metrics.packet_count; duration_seconds = $metrics.duration_seconds; protocol_counts = $metrics.protocol_counts; visibility = $metrics.visibility }
        } catch { $code = if ($_.Exception.Message -eq 'invalid_report_schema') { 'invalid_report_schema' } elseif ($_.Exception.Message -eq 'output_reparse_point') { 'output_reparse_point' } else { 'inspector_failed' }; $entry = New-FailedEntry $candidate.Ordinal $sha $size $code }
        finally { Remove-ChildReports $outputPath }
        Set-Entry $entries $entry; Add-ToHistogram $histogram $entry $candidate.Quartile; $processedSinceCheckpoint++
        if ($processedSinceCheckpoint -ge 100) { Save-AtomicJson ([ordered]@{ schema_version = 1; state_id = $StateId; entries = @($entries) }) $stateFile; $processedSinceCheckpoint = 0 }
    }
    Save-AtomicJson ([ordered]@{ schema_version = 1; state_id = $StateId; entries = @($entries) }) $stateFile; $publicPath = Join-Path $outputPath ('pcap-recon-' + $ReconId + '.json'); Assert-NoReparse $publicPath 'output_reparse_point'; Save-AtomicJson $histogram $publicPath; Write-Output ('pcap_recon_result=' + $ReconId); exit 0
}
catch { $code = 'unexpected_failure'; if ($script:ErrorCodes -contains $_.Exception.Message) { $code = $_.Exception.Message }; Write-Output ('pcap_recon_error=' + $code); exit 2 }
